# Signatories
This proposal is supported by a growing community of researchers and practitioners committed to improving camera trap data workflows in R. Letters of support have been received from the Zoological Society of London, the Laboratory of Applied Ecology at the University of Abomey-Calavi.

## Project team
The ct project will be led by me, ecological data scientist at the Laboratory of Applied Ecology (University of Abomey-Calavi) with extensive experience in ecological data management, statistical modeling, and open-source software development. I'm the creator and maintainer of [nimo](https://nimo.naben.org/), and [redlist](https://stangandaho.github.io/redlist/index.html) (now on CRAN), as well as software tools for machine learning and ecological monitoring such as [Declas](https://github.com/stangandaho/declas). My expertise in R package development, computer vision, and reproducible research workflows ensures that the project will be delivered to high technical and usability standards.

Prof. Marcus Rowcliffe (Zoological Society of London) and Damiano Oldoni (Research Institute for Nature and Forest, Belgium) will remain members of the project team, providing technical input and testing support. Their continued involvement guarantees that the package stays relevant to the broader camera trap data community.


## Contributors
<!--
Who are the people who have actively helped with this proposal but
won't necessarily be on the core project team later?
-->

## Consulted
<!--
Who has been given the opportunity to provide feedback on the
proposal? This should include any R Consortium & ISC members who the
proposal has been discussed with.
-->

