---
bibliography: references.bib
---

# The Problem
Camera traps are central to modern ecological research, conservation monitoring, and wildlife management, generating vast datasets that must be processed, summarized, and analyzed efficiently. Processing and analyzing camera trap data in R often requires multiple steps, from cleaning raw data to statistical modeling and visualization. However, the current R ecosystem for camera trap data remains fragmented. Researchers often combine multiple packages such as *camtrapR* [@camtrapR] for data management, *activity* for animal diel activity patterns [@activity], *unmarked* or *secr* for occupancy and capture–recapture modeling [@unmarked1; @unmarked2; @secr]. New methodologies, such as deep learning-assisted species identification, are often siloed in standalone tools *CameraTrapDetectoR* [@CameraTrapDetectoR]. The absence of a cohesive pipeline hinders innovation. Additionally, no existing R package natively integrates MegaDetector [@beery2019efficient], for object detection, providing full support for both images and videos, and offers a Shiny application that combines automated computer-vision processing with manual annotation and metadata management in a single workflow. MegaDetector’s versatility makes it an appealing option for a wide variety of camera trap projects, and its use and popularity have been rapidly growing worldwide [@LEORNA2022101876]. By integrating existing tools with novel approaches—such as those under development in the *ct* package, we plan to create an "all-in-one" platform that streamlines workflows, reduces redundancy, and democratizes access to advanced analytical methods. The package aims to provide a modern, tidyverse-friendly workflow for camera trap data analysis. Using tidy evaluation principles, it enables users to efficiently manipulate and transform datasets. Additionally, it integrates seamlessly with ggplot2 [@ggplot2], allowing users to generate highly customizable visualizations. This project will directly benefit ecologists, conservationists, and educators who rely on R for reproducible research but currently face unnecessary complexity in managing camera trap data.  